// src/app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-calendar/dist/Calendar.css';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        {/* Header */}
        <Header />
        {/* Body */}
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
