// src/app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-calendar/dist/Calendar.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import AuthProvider from '@/components/auth/AuthProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          {/* Header */}
          <Header />
          {/* Body */}
          {children}
          {/* Footer */}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
